# Generated by Django 3.2 on 2022-10-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20221012_0123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('сan_have_piece_of_pizza', 'Может съесть кусочек пиццы')]},
        ),
    ]
