# Generated by Django 3.2 on 2022-10-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rename_tags_article_tags_old'),
    ]

    operations = [
    ]
