# Generated by Django 3.2 on 2022-10-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20221006_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='webapp.Tag'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags_old',
            field=models.ManyToManyField(blank=True, related_name='article_set', through='webapp.ArticleTag', to='webapp.Tag'),
        ),
    ]
